package custom.orm.utils;

import java.lang.reflect.*;
import java.util.ArrayList;
import java.util.List;

import custom.orm.db.utils.annotations.*;

public class ReflectUtil {
    private Class<?> entityClass;

    public ReflectUtil(Class<?> entityClass) {
        this.entityClass = entityClass;
    }

    public Class<?> getEntityClass() {
        return entityClass;
    }

    public void setEntityClass(Class<?> entityClass) {
        this.entityClass = entityClass;
    }

    public String getTableName() throws Exception {
        if (!this.getEntityClass().isAnnotationPresent(Entity.class)) {
            throw new IllegalArgumentException("Reflect util entity class must be annotated @Entity");
        }

        Entity entityAnnotation = this.getEntityClass().getAnnotation(Entity.class);
        String tableName = entityAnnotation.tableName();
        if (tableName.isBlank()) {
            // means no tableName was set, so we use the class's name, to lowercase
            tableName = this.getEntityClass().getSimpleName().toLowerCase();
        }

        return tableName.trim();
    }

    public Field[] getColumns(boolean excludeAuto) {
        List<Field> fieldList = new ArrayList<>();

        Field[] allDeclared = this.getEntityClass().getDeclaredFields();
        for (Field field : allDeclared) {
            if ((excludeAuto && !field.isAnnotationPresent(AutoGenerated.class)) || !excludeAuto) {
                if (!field.isAnnotationPresent(NotMapped.class)) {
                    
                    fieldList.add(field);
                }
            }
        }

        Object[] tempArr = fieldList.toArray();

        Field[] results = new Field[tempArr.length];
        for (int i = 0; i < tempArr.length; i++) {
            results[i] = (Field) tempArr[i];
        }

        return results;
    }

    private String getColumnName(Field f) {
        if (f.isAnnotationPresent(Column.class)) {
            Column c = f.getAnnotation(Column.class);
            return c.name();
        } else {
            return f.getName().toLowerCase();
        }
    }

    public String[] getColumnNames(Field[] fields) {
        if (fields == null) {
            fields = this.getColumns(true);
        }

        String[] results = new String[fields.length];
        for (int i = 0; i < results.length; i++) {
            results[i] = getColumnName(fields[i]);
        }

        return results;
    }

    public String getColumnLineup(String[] columnNames) {
        if (columnNames == null) {
            columnNames = getColumnNames(null);
        }
        return String.join(", ", columnNames);
    }

    public String formInsertQuery(Field[] fields) throws Exception {
        String sql = "INSERT INTO " + getTableName() + " (";

        if (fields == null) {
            fields = this.getColumns(true);
        }

        String[] colNames = getColumnNames(fields);
        String lineup = getColumnLineup(colNames);
        String questionMarks = String.join(", ", "?".repeat(colNames.length).split(""));

        sql += lineup + ") VALUES (" + questionMarks + ")";

        return sql;
    }

    public static String getGetSetName(Field f, String method) {
        String name = f.getName();
        String capitalizedName = name.substring(0, 1).toUpperCase() + name.substring(1);

        return method.toLowerCase() + capitalizedName;
    }

    public Field getIdCol() {
        Field[] allFields = this.getEntityClass().getDeclaredFields();
        for (Field field : allFields) {
            if (field.isAnnotationPresent(Id.class)) {
                return field;
            }
        }
        return null;
    }

    public String getIdColName(Field idField) {
        if (idField == null) {
            idField = getIdCol();
        }

        return getColumnName(idField);
    }

}
